#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MuaBanXe")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertNoiDungTin(NoiDungTin instance);
  partial void UpdateNoiDungTin(NoiDungTin instance);
  partial void DeleteNoiDungTin(NoiDungTin instance);
  partial void InsertAccount(Account instance);
  partial void UpdateAccount(Account instance);
  partial void DeleteAccount(Account instance);
  partial void InsertHangXe(HangXe instance);
  partial void UpdateHangXe(HangXe instance);
  partial void DeleteHangXe(HangXe instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MuaBanXeConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<NoiDungTin> NoiDungTins
	{
		get
		{
			return this.GetTable<NoiDungTin>();
		}
	}
	
	public System.Data.Linq.Table<Account> Accounts
	{
		get
		{
			return this.GetTable<Account>();
		}
	}
	
	public System.Data.Linq.Table<HangXe> HangXes
	{
		get
		{
			return this.GetTable<HangXe>();
		}
	}
	
	public System.Data.Linq.Table<TinhThanh> TinhThanhs
	{
		get
		{
			return this.GetTable<TinhThanh>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NoiDungTin")]
public partial class NoiDungTin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _TieuDe;
	
	private decimal _GiaBan;
	
	private string _NoiBan;
	
	private System.DateTime _NgayDang;
	
	private string _NoiDung;
	
	private System.Nullable<int> _MaHangXe;
	
	private System.Nullable<bool> _Duyet;
	
	private System.Nullable<int> _MaUser;
	
	private System.Nullable<bool> _DaBan;
	
	private System.Data.Linq.Binary _HinhAnh;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnGiaBanChanging(decimal value);
    partial void OnGiaBanChanged();
    partial void OnNoiBanChanging(string value);
    partial void OnNoiBanChanged();
    partial void OnNgayDangChanging(System.DateTime value);
    partial void OnNgayDangChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnMaHangXeChanging(System.Nullable<int> value);
    partial void OnMaHangXeChanged();
    partial void OnDuyetChanging(System.Nullable<bool> value);
    partial void OnDuyetChanged();
    partial void OnMaUserChanging(System.Nullable<int> value);
    partial void OnMaUserChanged();
    partial void OnDaBanChanging(System.Nullable<bool> value);
    partial void OnDaBanChanged();
    partial void OnHinhAnhChanging(System.Data.Linq.Binary value);
    partial void OnHinhAnhChanged();
    #endregion
	
	public NoiDungTin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string TieuDe
	{
		get
		{
			return this._TieuDe;
		}
		set
		{
			if ((this._TieuDe != value))
			{
				this.OnTieuDeChanging(value);
				this.SendPropertyChanging();
				this._TieuDe = value;
				this.SendPropertyChanged("TieuDe");
				this.OnTieuDeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Money NOT NULL")]
	public decimal GiaBan
	{
		get
		{
			return this._GiaBan;
		}
		set
		{
			if ((this._GiaBan != value))
			{
				this.OnGiaBanChanging(value);
				this.SendPropertyChanging();
				this._GiaBan = value;
				this.SendPropertyChanged("GiaBan");
				this.OnGiaBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string NoiBan
	{
		get
		{
			return this._NoiBan;
		}
		set
		{
			if ((this._NoiBan != value))
			{
				this.OnNoiBanChanging(value);
				this.SendPropertyChanging();
				this._NoiBan = value;
				this.SendPropertyChanged("NoiBan");
				this.OnNoiBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime NOT NULL")]
	public System.DateTime NgayDang
	{
		get
		{
			return this._NgayDang;
		}
		set
		{
			if ((this._NgayDang != value))
			{
				this.OnNgayDangChanging(value);
				this.SendPropertyChanging();
				this._NgayDang = value;
				this.SendPropertyChanged("NgayDang");
				this.OnNgayDangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string NoiDung
	{
		get
		{
			return this._NoiDung;
		}
		set
		{
			if ((this._NoiDung != value))
			{
				this.OnNoiDungChanging(value);
				this.SendPropertyChanging();
				this._NoiDung = value;
				this.SendPropertyChanged("NoiDung");
				this.OnNoiDungChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangXe", DbType="Int")]
	public System.Nullable<int> MaHangXe
	{
		get
		{
			return this._MaHangXe;
		}
		set
		{
			if ((this._MaHangXe != value))
			{
				this.OnMaHangXeChanging(value);
				this.SendPropertyChanging();
				this._MaHangXe = value;
				this.SendPropertyChanged("MaHangXe");
				this.OnMaHangXeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duyet", DbType="Bit")]
	public System.Nullable<bool> Duyet
	{
		get
		{
			return this._Duyet;
		}
		set
		{
			if ((this._Duyet != value))
			{
				this.OnDuyetChanging(value);
				this.SendPropertyChanging();
				this._Duyet = value;
				this.SendPropertyChanged("Duyet");
				this.OnDuyetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaUser", DbType="Int")]
	public System.Nullable<int> MaUser
	{
		get
		{
			return this._MaUser;
		}
		set
		{
			if ((this._MaUser != value))
			{
				this.OnMaUserChanging(value);
				this.SendPropertyChanging();
				this._MaUser = value;
				this.SendPropertyChanged("MaUser");
				this.OnMaUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaBan", DbType="Bit")]
	public System.Nullable<bool> DaBan
	{
		get
		{
			return this._DaBan;
		}
		set
		{
			if ((this._DaBan != value))
			{
				this.OnDaBanChanging(value);
				this.SendPropertyChanging();
				this._DaBan = value;
				this.SendPropertyChanged("DaBan");
				this.OnDaBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary HinhAnh
	{
		get
		{
			return this._HinhAnh;
		}
		set
		{
			if ((this._HinhAnh != value))
			{
				this.OnHinhAnhChanging(value);
				this.SendPropertyChanging();
				this._HinhAnh = value;
				this.SendPropertyChanged("HinhAnh");
				this.OnHinhAnhChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _HoTen;
	
	private string _MatKhau;
	
	private string _Sdt;
	
	private string _DiaChi;
	
	private string _Email;
	
	private string _TinhThanh;
	
	private System.Nullable<int> _RoleID;
	
	private System.Nullable<bool> _Active;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    partial void OnRoleIDChanging(System.Nullable<int> value);
    partial void OnRoleIDChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
	
	public Account()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string HoTen
	{
		get
		{
			return this._HoTen;
		}
		set
		{
			if ((this._HoTen != value))
			{
				this.OnHoTenChanging(value);
				this.SendPropertyChanging();
				this._HoTen = value;
				this.SendPropertyChanged("HoTen");
				this.OnHoTenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string MatKhau
	{
		get
		{
			return this._MatKhau;
		}
		set
		{
			if ((this._MatKhau != value))
			{
				this.OnMatKhauChanging(value);
				this.SendPropertyChanging();
				this._MatKhau = value;
				this.SendPropertyChanged("MatKhau");
				this.OnMatKhauChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NChar(11) NOT NULL", CanBeNull=false)]
	public string Sdt
	{
		get
		{
			return this._Sdt;
		}
		set
		{
			if ((this._Sdt != value))
			{
				this.OnSdtChanging(value);
				this.SendPropertyChanging();
				this._Sdt = value;
				this.SendPropertyChanged("Sdt");
				this.OnSdtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(50)")]
	public string TinhThanh
	{
		get
		{
			return this._TinhThanh;
		}
		set
		{
			if ((this._TinhThanh != value))
			{
				this.OnTinhThanhChanging(value);
				this.SendPropertyChanging();
				this._TinhThanh = value;
				this.SendPropertyChanged("TinhThanh");
				this.OnTinhThanhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int")]
	public System.Nullable<int> RoleID
	{
		get
		{
			return this._RoleID;
		}
		set
		{
			if ((this._RoleID != value))
			{
				this.OnRoleIDChanging(value);
				this.SendPropertyChanging();
				this._RoleID = value;
				this.SendPropertyChanged("RoleID");
				this.OnRoleIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
	public System.Nullable<bool> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangXe")]
public partial class HangXe : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _HangXe1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHangXe1Changing(string value);
    partial void OnHangXe1Changed();
    #endregion
	
	public HangXe()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HangXe", Storage="_HangXe1", DbType="NVarChar(50)")]
	public string HangXe1
	{
		get
		{
			return this._HangXe1;
		}
		set
		{
			if ((this._HangXe1 != value))
			{
				this.OnHangXe1Changing(value);
				this.SendPropertyChanging();
				this._HangXe1 = value;
				this.SendPropertyChanged("HangXe1");
				this.OnHangXe1Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinhThanh")]
public partial class TinhThanh
{
	
	private string _Id;
	
	private string _Tên;
	
	private string _Loại;
	
	public TinhThanh()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NChar(10) NOT NULL", CanBeNull=false)]
	public string Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tên", DbType="NVarChar(255)")]
	public string Tên
	{
		get
		{
			return this._Tên;
		}
		set
		{
			if ((this._Tên != value))
			{
				this._Tên = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loại", DbType="NVarChar(255)")]
	public string Loại
	{
		get
		{
			return this._Loại;
		}
		set
		{
			if ((this._Loại != value))
			{
				this._Loại = value;
			}
		}
	}
}
#pragma warning restore 1591
